module.exports = function toReadable(number) {
    let users = [
        { id: 0, name: "zero" },
        { id: 1, name: "one" },
        { id: 2, name: "two" },
        { id: 3, name: "three" },
        { id: 4, name: "four" },
        { id: 5, name: "five" },
        { id: 6, name: "six" },
        { id: 7, name: "seven" },
        { id: 8, name: "eight" },
        { id: 9, name: "nine" },
        { id: 10, name: "ten" },
        { id: 11, name: "eleven" },
        { id: 12, name: "twelve" },
        { id: 13, name: "thirteen" },
        { id: 14, name: "fourteen" },
        { id: 15, name: "fifteen" },
        { id: 16, name: "sixteen" },
        { id: 17, name: "seventeen" },
        { id: 18, name: "eighteen" },
        { id: 19, name: "nineteen" },
        { id: 20, name: "twenty" },
        { id: 21, name: "twenty one" },
        { id: 22, name: "twenty two" },
        { id: 23, name: "twenty three" },
        { id: 24, name: "twenty four" },
        { id: 25, name: "twenty five" },
        { id: 26, name: "twenty six" },
        { id: 27, name: "twenty seven" },
        { id: 28, name: "twenty eight" },
        { id: 29, name: "twenty nine" },
        { id: 30, name: "thirty" },
        { id: 31, name: "thirty one" },
        { id: 32, name: "thirty two" },
        { id: 33, name: "thirty three" },
        { id: 34, name: "thirty four" },
        { id: 35, name: "thirty five" },
        { id: 36, name: "thirty six" },
        { id: 37, name: "thirty seven" },
        { id: 38, name: "thirty eight" },
        { id: 39, name: "thirty nine" },
        { id: 40, name: "forty" },
        { id: 41, name: "forty one" },
        { id: 42, name: "forty two" },
        { id: 43, name: "forty three" },
        { id: 44, name: "forty four" },
        { id: 45, name: "forty five" },
        { id: 46, name: "forty six" },
        { id: 47, name: "forty seven" },
        { id: 48, name: "forty eight" },
        { id: 49, name: "forty nine" },
        { id: 50, name: "fifty" },
        { id: 51, name: "fifty one" },
        { id: 52, name: "fifty two" },
        { id: 53, name: "fifty three" },
        { id: 54, name: "fifty four" },
        { id: 55, name: "fifty five" },
        { id: 56, name: "fifty six" },
        { id: 57, name: "fifty seven" },
        { id: 58, name: "fifty eight" },
        { id: 59, name: "fifty nine" },
        { id: 60, name: "sixty" },
        { id: 61, name: "sixty one" },
        { id: 62, name: "sixty two" },
        { id: 63, name: "sixty three" },
        { id: 64, name: "sixty four" },
        { id: 65, name: "sixty five" },
        { id: 66, name: "sixty six" },
        { id: 67, name: "sixty seven" },
        { id: 68, name: "sixty eight" },
        { id: 69, name: "sixty nine" },
        { id: 70, name: "seventy" },
        { id: 71, name: "seventy one" },
        { id: 72, name: "seventy two" },
        { id: 73, name: "seventy three" },
        { id: 74, name: "seventy four" },
        { id: 75, name: "seventy five" },
        { id: 76, name: "seventy six" },
        { id: 77, name: "seventy seven" },
        { id: 78, name: "seventy eight" },
        { id: 79, name: "seventy nine" },
        { id: 80, name: "eighty" },
        { id: 81, name: "eighty one" },
        { id: 82, name: "eighty two" },
        { id: 83, name: "eighty three" },
        { id: 84, name: "eighty four" },
        { id: 85, name: "eighty five" },
        { id: 86, name: "eighty six" },
        { id: 87, name: "eighty seven" },
        { id: 88, name: "eighty eight" },
        { id: 89, name: "eighty nine" },
        { id: 90, name: "ninety" },
        { id: 91, name: "ninety one" },
        { id: 92, name: "ninety two" },
        { id: 93, name: "ninety three" },
        { id: 94, name: "ninety four" },
        { id: 95, name: "ninety five" },
        { id: 96, name: "ninety six" },
        { id: 97, name: "ninety seven" },
        { id: 98, name: "ninety eight" },
        { id: 99, name: "ninety nine" },
        { id: 100, name: "one hundred" },
        { id: 101, name: "one hundred one" },
        { id: 102, name: "one hundred two" },
        { id: 103, name: "one hundred three" },
        { id: 104, name: "one hundred four" },
        { id: 105, name: "one hundred five" },
        { id: 106, name: "one hundred six" },
        { id: 107, name: "one hundred seven" },
        { id: 108, name: "one hundred eight" },
        { id: 109, name: "one hundred nine" },
        { id: 110, name: "one hundred ten" },
        { id: 111, name: "one hundred eleven" },
        { id: 112, name: "one hundred twelve" },
        { id: 113, name: "one hundred thirteen" },
        { id: 114, name: "one hundred fourteen" },
        { id: 115, name: "one hundred fifteen" },
        { id: 116, name: "one hundred sixteen" },
        { id: 117, name: "one hundred seventeen" },
        { id: 118, name: "one hundred eighteen" },
        { id: 119, name: "one hundred nineteen" },
        { id: 120, name: "one hundred twenty" },
        { id: 121, name: "one hundred twenty one" },
        { id: 122, name: "one hundred twenty two" },
        { id: 123, name: "one hundred twenty three" },
        { id: 124, name: "one hundred twenty four" },
        { id: 125, name: "one hundred twenty five" },
        { id: 126, name: "one hundred twenty six" },
        { id: 127, name: "one hundred twenty seven" },
        { id: 128, name: "one hundred twenty eight" },
        { id: 129, name: "one hundred twenty nine" },
        { id: 130, name: "one hundred thirty" },
        { id: 131, name: "one hundred thirty one" },
        { id: 132, name: "one hundred thirty two" },
        { id: 133, name: "one hundred thirty three" },
        { id: 134, name: "one hundred thirty four" },
        { id: 135, name: "one hundred thirty five" },
        { id: 136, name: "one hundred thirty six" },
        { id: 137, name: "one hundred thirty seven" },
        { id: 138, name: "one hundred thirty eight" },
        { id: 139, name: "one hundred thirty nine" },
        { id: 140, name: "one hundred forty" },
        { id: 141, name: "one hundred forty one" },
        { id: 142, name: "one hundred forty two" },
        { id: 143, name: "one hundred forty three" },
        { id: 144, name: "one hundred forty four" },
        { id: 145, name: "one hundred forty five" },
        { id: 146, name: "one hundred forty six" },
        { id: 147, name: "one hundred forty seven" },
        { id: 148, name: "one hundred forty eight" },
        { id: 149, name: "one hundred forty nine" },
        { id: 150, name: "one hundred fifty" },
        { id: 151, name: "one hundred fifty one" },
        { id: 152, name: "one hundred fifty two" },
        { id: 153, name: "one hundred fifty three" },
        { id: 154, name: "one hundred fifty four" },
        { id: 155, name: "one hundred fifty five" },
        { id: 156, name: "one hundred fifty six" },
        { id: 157, name: "one hundred fifty seven" },
        { id: 158, name: "one hundred fifty eight" },
        { id: 159, name: "one hundred fifty nine" },
        { id: 160, name: "one hundred sixty" },
        { id: 161, name: "one hundred sixty one" },
        { id: 162, name: "one hundred sixty two" },
        { id: 163, name: "one hundred sixty three" },
        { id: 164, name: "one hundred sixty four" },
        { id: 165, name: "one hundred sixty five" },
        { id: 166, name: "one hundred sixty six" },
        { id: 167, name: "one hundred sixty seven" },
        { id: 168, name: "one hundred sixty eight" },
        { id: 169, name: "one hundred sixty nine" },
        { id: 170, name: "one hundred seventy" },
        { id: 171, name: "one hundred seventy one" },
        { id: 172, name: "one hundred seventy two" },
        { id: 173, name: "one hundred seventy three" },
        { id: 174, name: "one hundred seventy four" },
        { id: 175, name: "one hundred seventy five" },
        { id: 176, name: "one hundred seventy six" },
        { id: 177, name: "one hundred seventy seven" },
        { id: 178, name: "one hundred seventy eight" },
        { id: 179, name: "one hundred seventy nine" },
        { id: 180, name: "one hundred eighty" },
        { id: 181, name: "one hundred eighty one" },
        { id: 182, name: "one hundred eighty two" },
        { id: 183, name: "one hundred eighty three" },
        { id: 184, name: "one hundred eighty four" },
        { id: 185, name: "one hundred eighty five" },
        { id: 186, name: "one hundred eighty six" },
        { id: 187, name: "one hundred eighty seven" },
        { id: 188, name: "one hundred eighty eight" },
        { id: 189, name: "one hundred eighty nine" },
        { id: 190, name: "one hundred ninety" },
        { id: 191, name: "one hundred ninety one" },
        { id: 192, name: "one hundred ninety two" },
        { id: 193, name: "one hundred ninety three" },
        { id: 194, name: "one hundred ninety four" },
        { id: 195, name: "one hundred ninety five" },
        { id: 196, name: "one hundred ninety six" },
        { id: 197, name: "one hundred ninety seven" },
        { id: 198, name: "one hundred ninety eight" },
        { id: 199, name: "one hundred ninety nine" },
        { id: 200, name: "two hundred" },
        { id: 201, name: "two hundred one" },
        { id: 202, name: "two hundred two" },
        { id: 203, name: "two hundred three" },
        { id: 204, name: "two hundred four" },
        { id: 205, name: "two hundred five" },
        { id: 206, name: "two hundred six" },
        { id: 207, name: "two hundred seven" },
        { id: 208, name: "two hundred eight" },
        { id: 209, name: "two hundred nine" },
        { id: 210, name: "two hundred ten" },
        { id: 211, name: "two hundred eleven" },
        { id: 212, name: "two hundred twelve" },
        { id: 213, name: "two hundred thirteen" },
        { id: 214, name: "two hundred fourteen" },
        { id: 215, name: "two hundred fifteen" },
        { id: 216, name: "two hundred sixteen" },
        { id: 217, name: "two hundred seventeen" },
        { id: 218, name: "two hundred eighteen" },
        { id: 219, name: "two hundred nineteen" },
        { id: 220, name: "two hundred twenty" },
        { id: 221, name: "two hundred twenty one" },
        { id: 222, name: "two hundred twenty two" },
        { id: 223, name: "two hundred twenty three" },
        { id: 224, name: "two hundred twenty four" },
        { id: 225, name: "two hundred twenty five" },
        { id: 226, name: "two hundred twenty six" },
        { id: 227, name: "two hundred twenty seven" },
        { id: 228, name: "two hundred twenty eight" },
        { id: 229, name: "two hundred twenty nine" },
        { id: 230, name: "two hundred thirty" },
        { id: 231, name: "two hundred thirty one" },
        { id: 232, name: "two hundred thirty two" },
        { id: 233, name: "two hundred thirty three" },
        { id: 234, name: "two hundred thirty four" },
        { id: 235, name: "two hundred thirty five" },
        { id: 236, name: "two hundred thirty six" },
        { id: 237, name: "two hundred thirty seven" },
        { id: 238, name: "two hundred thirty eight" },
        { id: 239, name: "two hundred thirty nine" },
        { id: 240, name: "two hundred forty" },
        { id: 241, name: "two hundred forty one" },
        { id: 242, name: "two hundred forty two" },
        { id: 243, name: "two hundred forty three" },
        { id: 244, name: "two hundred forty four" },
        { id: 245, name: "two hundred forty five" },
        { id: 246, name: "two hundred forty six" },
        { id: 247, name: "two hundred forty seven" },
        { id: 248, name: "two hundred forty eight" },
        { id: 249, name: "two hundred forty nine" },
        { id: 250, name: "two hundred fifty" },
        { id: 251, name: "two hundred fifty one" },
        { id: 252, name: "two hundred fifty two" },
        { id: 253, name: "two hundred fifty three" },
        { id: 254, name: "two hundred fifty four" },
        { id: 255, name: "two hundred fifty five" },
        { id: 256, name: "two hundred fifty six" },
        { id: 257, name: "two hundred fifty seven" },
        { id: 258, name: "two hundred fifty eight" },
        { id: 259, name: "two hundred fifty nine" },
        { id: 260, name: "two hundred sixty" },
        { id: 261, name: "two hundred sixty one" },
        { id: 262, name: "two hundred sixty two" },
        { id: 263, name: "two hundred sixty three" },
        { id: 264, name: "two hundred sixty four" },
        { id: 265, name: "two hundred sixty five" },
        { id: 266, name: "two hundred sixty six" },
        { id: 267, name: "two hundred sixty seven" },
        { id: 268, name: "two hundred sixty eight" },
        { id: 269, name: "two hundred sixty nine" },
        { id: 270, name: "two hundred seventy" },
        { id: 271, name: "two hundred seventy one" },
        { id: 272, name: "two hundred seventy two" },
        { id: 273, name: "two hundred seventy three" },
        { id: 274, name: "two hundred seventy four" },
        { id: 275, name: "two hundred seventy five" },
        { id: 276, name: "two hundred seventy six" },
        { id: 277, name: "two hundred seventy seven" },
        { id: 278, name: "two hundred seventy eight" },
        { id: 279, name: "two hundred seventy nine" },
        { id: 280, name: "two hundred eighty" },
        { id: 281, name: "two hundred eighty one" },
        { id: 282, name: "two hundred eighty two" },
        { id: 283, name: "two hundred eighty three" },
        { id: 284, name: "two hundred eighty four" },
        { id: 285, name: "two hundred eighty five" },
        { id: 286, name: "two hundred eighty six" },
        { id: 287, name: "two hundred eighty seven" },
        { id: 288, name: "two hundred eighty eight" },
        { id: 289, name: "two hundred eighty nine" },
        { id: 290, name: "two hundred ninety" },
        { id: 291, name: "two hundred ninety one" },
        { id: 292, name: "two hundred ninety two" },
        { id: 293, name: "two hundred ninety three" },
        { id: 294, name: "two hundred ninety four" },
        { id: 295, name: "two hundred ninety five" },
        { id: 296, name: "two hundred ninety six" },
        { id: 297, name: "two hundred ninety seven" },
        { id: 298, name: "two hundred ninety eight" },
        { id: 299, name: "two hundred ninety nine" },
        { id: 300, name: "three hundred" },
        { id: 301, name: "three hundred one" },
        { id: 302, name: "three hundred two" },
        { id: 303, name: "three hundred three" },
        { id: 304, name: "three hundred four" },
        { id: 305, name: "three hundred five" },
        { id: 306, name: "three hundred six" },
        { id: 307, name: "three hundred seven" },
        { id: 308, name: "three hundred eight" },
        { id: 309, name: "three hundred nine" },
        { id: 310, name: "three hundred ten" },
        { id: 311, name: "three hundred eleven" },
        { id: 312, name: "three hundred twelve" },
        { id: 313, name: "three hundred thirteen" },
        { id: 314, name: "three hundred fourteen" },
        { id: 315, name: "three hundred fifteen" },
        { id: 316, name: "three hundred sixteen" },
        { id: 317, name: "three hundred seventeen" },
        { id: 318, name: "three hundred eighteen" },
        { id: 319, name: "three hundred nineteen" },
        { id: 320, name: "three hundred twenty" },
        { id: 321, name: "three hundred twenty one" },
        { id: 322, name: "three hundred twenty two" },
        { id: 323, name: "three hundred twenty three" },
        { id: 324, name: "three hundred twenty four" },
        { id: 325, name: "three hundred twenty five" },
        { id: 326, name: "three hundred twenty six" },
        { id: 327, name: "three hundred twenty seven" },
        { id: 328, name: "three hundred twenty eight" },
        { id: 329, name: "three hundred twenty nine" },
        { id: 330, name: "three hundred thirty" },
        { id: 331, name: "three hundred thirty one" },
        { id: 332, name: "three hundred thirty two" },
        { id: 333, name: "three hundred thirty three" },
        { id: 334, name: "three hundred thirty four" },
        { id: 335, name: "three hundred thirty five" },
        { id: 336, name: "three hundred thirty six" },
        { id: 337, name: "three hundred thirty seven" },
        { id: 338, name: "three hundred thirty eight" },
        { id: 339, name: "three hundred thirty nine" },
        { id: 340, name: "three hundred forty" },
        { id: 341, name: "three hundred forty one" },
        { id: 342, name: "three hundred forty two" },
        { id: 343, name: "three hundred forty three" },
        { id: 344, name: "three hundred forty four" },
        { id: 345, name: "three hundred forty five" },
        { id: 346, name: "three hundred forty six" },
        { id: 347, name: "three hundred forty seven" },
        { id: 348, name: "three hundred forty eight" },
        { id: 349, name: "three hundred forty nine" },
        { id: 350, name: "three hundred fifty" },
        { id: 351, name: "three hundred fifty one" },
        { id: 352, name: "three hundred fifty two" },
        { id: 353, name: "three hundred fifty three" },
        { id: 354, name: "three hundred fifty four" },
        { id: 355, name: "three hundred fifty five" },
        { id: 356, name: "three hundred fifty six" },
        { id: 357, name: "three hundred fifty seven" },
        { id: 358, name: "three hundred fifty eight" },
        { id: 359, name: "three hundred fifty nine" },
        { id: 360, name: "three hundred sixty" },
        { id: 361, name: "three hundred sixty one" },
        { id: 362, name: "three hundred sixty two" },
        { id: 363, name: "three hundred sixty three" },
        { id: 364, name: "three hundred sixty four" },
        { id: 365, name: "three hundred sixty five" },
        { id: 366, name: "three hundred sixty six" },
        { id: 367, name: "three hundred sixty seven" },
        { id: 368, name: "three hundred sixty eight" },
        { id: 369, name: "three hundred sixty nine" },
        { id: 370, name: "three hundred seventy" },
        { id: 371, name: "three hundred seventy one" },
        { id: 372, name: "three hundred seventy two" },
        { id: 373, name: "three hundred seventy three" },
        { id: 374, name: "three hundred seventy four" },
        { id: 375, name: "three hundred seventy five" },
        { id: 376, name: "three hundred seventy six" },
        { id: 377, name: "three hundred seventy seven" },
        { id: 378, name: "three hundred seventy eight" },
        { id: 379, name: "three hundred seventy nine" },
        { id: 380, name: "three hundred eighty" },
        { id: 381, name: "three hundred eighty one" },
        { id: 382, name: "three hundred eighty two" },
        { id: 383, name: "three hundred eighty three" },
        { id: 384, name: "three hundred eighty four" },
        { id: 385, name: "three hundred eighty five" },
        { id: 386, name: "three hundred eighty six" },
        { id: 387, name: "three hundred eighty seven" },
        { id: 388, name: "three hundred eighty eight" },
        { id: 389, name: "three hundred eighty nine" },
        { id: 390, name: "three hundred ninety" },
        { id: 391, name: "three hundred ninety one" },
        { id: 392, name: "three hundred ninety two" },
        { id: 393, name: "three hundred ninety three" },
        { id: 394, name: "three hundred ninety four" },
        { id: 395, name: "three hundred ninety five" },
        { id: 396, name: "three hundred ninety six" },
        { id: 397, name: "three hundred ninety seven" },
        { id: 398, name: "three hundred ninety eight" },
        { id: 399, name: "three hundred ninety nine" },
        { id: 400, name: "four hundred" },
        { id: 401, name: "four hundred one" },
        { id: 402, name: "four hundred two" },
        { id: 403, name: "four hundred three" },
        { id: 404, name: "four hundred four" },
        { id: 405, name: "four hundred five" },
        { id: 406, name: "four hundred six" },
        { id: 407, name: "four hundred seven" },
        { id: 408, name: "four hundred eight" },
        { id: 409, name: "four hundred nine" },
        { id: 410, name: "four hundred ten" },
        { id: 411, name: "four hundred eleven" },
        { id: 412, name: "four hundred twelve" },
        { id: 413, name: "four hundred thirteen" },
        { id: 414, name: "four hundred fourteen" },
        { id: 415, name: "four hundred fifteen" },
        { id: 416, name: "four hundred sixteen" },
        { id: 417, name: "four hundred seventeen" },
        { id: 418, name: "four hundred eighteen" },
        { id: 419, name: "four hundred nineteen" },
        { id: 420, name: "four hundred twenty" },
        { id: 421, name: "four hundred twenty one" },
        { id: 422, name: "four hundred twenty two" },
        { id: 423, name: "four hundred twenty three" },
        { id: 424, name: "four hundred twenty four" },
        { id: 425, name: "four hundred twenty five" },
        { id: 426, name: "four hundred twenty six" },
        { id: 427, name: "four hundred twenty seven" },
        { id: 428, name: "four hundred twenty eight" },
        { id: 429, name: "four hundred twenty nine" },
        { id: 430, name: "four hundred thirty" },
        { id: 431, name: "four hundred thirty one" },
        { id: 432, name: "four hundred thirty two" },
        { id: 433, name: "four hundred thirty three" },
        { id: 434, name: "four hundred thirty four" },
        { id: 435, name: "four hundred thirty five" },
        { id: 436, name: "four hundred thirty six" },
        { id: 437, name: "four hundred thirty seven" },
        { id: 438, name: "four hundred thirty eight" },
        { id: 439, name: "four hundred thirty nine" },
        { id: 440, name: "four hundred forty" },
        { id: 441, name: "four hundred forty one" },
        { id: 442, name: "four hundred forty two" },
        { id: 443, name: "four hundred forty three" },
        { id: 444, name: "four hundred forty four" },
        { id: 445, name: "four hundred forty five" },
        { id: 446, name: "four hundred forty six" },
        { id: 447, name: "four hundred forty seven" },
        { id: 448, name: "four hundred forty eight" },
        { id: 449, name: "four hundred forty nine" },
        { id: 450, name: "four hundred fifty" },
        { id: 451, name: "four hundred fifty one" },
        { id: 452, name: "four hundred fifty two" },
        { id: 453, name: "four hundred fifty three" },
        { id: 454, name: "four hundred fifty four" },
        { id: 455, name: "four hundred fifty five" },
        { id: 456, name: "four hundred fifty six" },
        { id: 457, name: "four hundred fifty seven" },
        { id: 458, name: "four hundred fifty eight" },
        { id: 459, name: "four hundred fifty nine" },
        { id: 460, name: "four hundred sixty" },
        { id: 461, name: "four hundred sixty one" },
        { id: 462, name: "four hundred sixty two" },
        { id: 463, name: "four hundred sixty three" },
        { id: 464, name: "four hundred sixty four" },
        { id: 465, name: "four hundred sixty five" },
        { id: 466, name: "four hundred sixty six" },
        { id: 467, name: "four hundred sixty seven" },
        { id: 468, name: "four hundred sixty eight" },
        { id: 469, name: "four hundred sixty nine" },
        { id: 470, name: "four hundred seventy" },
        { id: 471, name: "four hundred seventy one" },
        { id: 472, name: "four hundred seventy two" },
        { id: 473, name: "four hundred seventy three" },
        { id: 474, name: "four hundred seventy four" },
        { id: 475, name: "four hundred seventy five" },
        { id: 476, name: "four hundred seventy six" },
        { id: 477, name: "four hundred seventy seven" },
        { id: 478, name: "four hundred seventy eight" },
        { id: 479, name: "four hundred seventy nine" },
        { id: 480, name: "four hundred eighty" },
        { id: 481, name: "four hundred eighty one" },
        { id: 482, name: "four hundred eighty two" },
        { id: 483, name: "four hundred eighty three" },
        { id: 484, name: "four hundred eighty four" },
        { id: 485, name: "four hundred eighty five" },
        { id: 486, name: "four hundred eighty six" },
        { id: 487, name: "four hundred eighty seven" },
        { id: 488, name: "four hundred eighty eight" },
        { id: 489, name: "four hundred eighty nine" },
        { id: 490, name: "four hundred ninety" },
        { id: 491, name: "four hundred ninety one" },
        { id: 492, name: "four hundred ninety two" },
        { id: 493, name: "four hundred ninety three" },
        { id: 494, name: "four hundred ninety four" },
        { id: 495, name: "four hundred ninety five" },
        { id: 496, name: "four hundred ninety six" },
        { id: 497, name: "four hundred ninety seven" },
        { id: 498, name: "four hundred ninety eight" },
        { id: 499, name: "four hundred ninety nine" },
        { id: 500, name: "five hundred" },
        { id: 501, name: "five hundred one" },
        { id: 502, name: "five hundred two" },
        { id: 503, name: "five hundred three" },
        { id: 504, name: "five hundred four" },
        { id: 505, name: "five hundred five" },
        { id: 506, name: "five hundred six" },
        { id: 507, name: "five hundred seven" },
        { id: 508, name: "five hundred eight" },
        { id: 509, name: "five hundred nine" },
        { id: 510, name: "five hundred ten" },
        { id: 511, name: "five hundred eleven" },
        { id: 512, name: "five hundred twelve" },
        { id: 513, name: "five hundred thirteen" },
        { id: 514, name: "five hundred fourteen" },
        { id: 515, name: "five hundred fifteen" },
        { id: 516, name: "five hundred sixteen" },
        { id: 517, name: "five hundred seventeen" },
        { id: 518, name: "five hundred eighteen" },
        { id: 519, name: "five hundred nineteen" },
        { id: 520, name: "five hundred twenty" },
        { id: 521, name: "five hundred twenty one" },
        { id: 522, name: "five hundred twenty two" },
        { id: 523, name: "five hundred twenty three" },
        { id: 524, name: "five hundred twenty four" },
        { id: 525, name: "five hundred twenty five" },
        { id: 526, name: "five hundred twenty six" },
        { id: 527, name: "five hundred twenty seven" },
        { id: 528, name: "five hundred twenty eight" },
        { id: 529, name: "five hundred twenty nine" },
        { id: 530, name: "five hundred thirty" },
        { id: 531, name: "five hundred thirty one" },
        { id: 532, name: "five hundred thirty two" },
        { id: 533, name: "five hundred thirty three" },
        { id: 534, name: "five hundred thirty four" },
        { id: 535, name: "five hundred thirty five" },
        { id: 536, name: "five hundred thirty six" },
        { id: 537, name: "five hundred thirty seven" },
        { id: 538, name: "five hundred thirty eight" },
        { id: 539, name: "five hundred thirty nine" },
        { id: 540, name: "five hundred forty" },
        { id: 541, name: "five hundred forty one" },
        { id: 542, name: "five hundred forty two" },
        { id: 543, name: "five hundred forty three" },
        { id: 544, name: "five hundred forty four" },
        { id: 545, name: "five hundred forty five" },
        { id: 546, name: "five hundred forty six" },
        { id: 547, name: "five hundred forty seven" },
        { id: 548, name: "five hundred forty eight" },
        { id: 549, name: "five hundred forty nine" },
        { id: 550, name: "five hundred fifty" },
        { id: 551, name: "five hundred fifty one" },
        { id: 552, name: "five hundred fifty two" },
        { id: 553, name: "five hundred fifty three" },
        { id: 554, name: "five hundred fifty four" },
        { id: 555, name: "five hundred fifty five" },
        { id: 556, name: "five hundred fifty six" },
        { id: 557, name: "five hundred fifty seven" },
        { id: 558, name: "five hundred fifty eight" },
        { id: 559, name: "five hundred fifty nine" },
        { id: 560, name: "five hundred sixty" },
        { id: 561, name: "five hundred sixty one" },
        { id: 562, name: "five hundred sixty two" },
        { id: 563, name: "five hundred sixty three" },
        { id: 564, name: "five hundred sixty four" },
        { id: 565, name: "five hundred sixty five" },
        { id: 566, name: "five hundred sixty six" },
        { id: 567, name: "five hundred sixty seven" },
        { id: 568, name: "five hundred sixty eight" },
        { id: 569, name: "five hundred sixty nine" },
        { id: 570, name: "five hundred seventy" },
        { id: 571, name: "five hundred seventy one" },
        { id: 572, name: "five hundred seventy two" },
        { id: 573, name: "five hundred seventy three" },
        { id: 574, name: "five hundred seventy four" },
        { id: 575, name: "five hundred seventy five" },
        { id: 576, name: "five hundred seventy six" },
        { id: 577, name: "five hundred seventy seven" },
        { id: 578, name: "five hundred seventy eight" },
        { id: 579, name: "five hundred seventy nine" },
        { id: 580, name: "five hundred eighty" },
        { id: 581, name: "five hundred eighty one" },
        { id: 582, name: "five hundred eighty two" },
        { id: 583, name: "five hundred eighty three" },
        { id: 584, name: "five hundred eighty four" },
        { id: 585, name: "five hundred eighty five" },
        { id: 586, name: "five hundred eighty six" },
        { id: 587, name: "five hundred eighty seven" },
        { id: 588, name: "five hundred eighty eight" },
        { id: 589, name: "five hundred eighty nine" },
        { id: 590, name: "five hundred ninety" },
        { id: 591, name: "five hundred ninety one" },
        { id: 592, name: "five hundred ninety two" },
        { id: 593, name: "five hundred ninety three" },
        { id: 594, name: "five hundred ninety four" },
        { id: 595, name: "five hundred ninety five" },
        { id: 596, name: "five hundred ninety six" },
        { id: 597, name: "five hundred ninety seven" },
        { id: 598, name: "five hundred ninety eight" },
        { id: 599, name: "five hundred ninety nine" },
        { id: 600, name: "six hundred" },
        { id: 601, name: "six hundred one" },
        { id: 602, name: "six hundred two" },
        { id: 603, name: "six hundred three" },
        { id: 604, name: "six hundred four" },
        { id: 605, name: "six hundred five" },
        { id: 606, name: "six hundred six" },
        { id: 607, name: "six hundred seven" },
        { id: 608, name: "six hundred eight" },
        { id: 609, name: "six hundred nine" },
        { id: 610, name: "six hundred ten" },
        { id: 611, name: "six hundred eleven" },
        { id: 612, name: "six hundred twelve" },
        { id: 613, name: "six hundred thirteen" },
        { id: 614, name: "six hundred fourteen" },
        { id: 615, name: "six hundred fifteen" },
        { id: 616, name: "six hundred sixteen" },
        { id: 617, name: "six hundred seventeen" },
        { id: 618, name: "six hundred eighteen" },
        { id: 619, name: "six hundred nineteen" },
        { id: 620, name: "six hundred twenty" },
        { id: 621, name: "six hundred twenty one" },
        { id: 622, name: "six hundred twenty two" },
        { id: 623, name: "six hundred twenty three" },
        { id: 624, name: "six hundred twenty four" },
        { id: 625, name: "six hundred twenty five" },
        { id: 626, name: "six hundred twenty six" },
        { id: 627, name: "six hundred twenty seven" },
        { id: 628, name: "six hundred twenty eight" },
        { id: 629, name: "six hundred twenty nine" },
        { id: 630, name: "six hundred thirty" },
        { id: 631, name: "six hundred thirty one" },
        { id: 632, name: "six hundred thirty two" },
        { id: 633, name: "six hundred thirty three" },
        { id: 634, name: "six hundred thirty four" },
        { id: 635, name: "six hundred thirty five" },
        { id: 636, name: "six hundred thirty six" },
        { id: 637, name: "six hundred thirty seven" },
        { id: 638, name: "six hundred thirty eight" },
        { id: 639, name: "six hundred thirty nine" },
        { id: 640, name: "six hundred forty" },
        { id: 641, name: "six hundred forty one" },
        { id: 642, name: "six hundred forty two" },
        { id: 643, name: "six hundred forty three" },
        { id: 644, name: "six hundred forty four" },
        { id: 645, name: "six hundred forty five" },
        { id: 646, name: "six hundred forty six" },
        { id: 647, name: "six hundred forty seven" },
        { id: 648, name: "six hundred forty eight" },
        { id: 649, name: "six hundred forty nine" },
        { id: 650, name: "six hundred fifty" },
        { id: 651, name: "six hundred fifty one" },
        { id: 652, name: "six hundred fifty two" },
        { id: 653, name: "six hundred fifty three" },
        { id: 654, name: "six hundred fifty four" },
        { id: 655, name: "six hundred fifty five" },
        { id: 656, name: "six hundred fifty six" },
        { id: 657, name: "six hundred fifty seven" },
        { id: 658, name: "six hundred fifty eight" },
        { id: 659, name: "six hundred fifty nine" },
        { id: 660, name: "six hundred sixty" },
        { id: 661, name: "six hundred sixty one" },
        { id: 662, name: "six hundred sixty two" },
        { id: 663, name: "six hundred sixty three" },
        { id: 664, name: "six hundred sixty four" },
        { id: 665, name: "six hundred sixty five" },
        { id: 666, name: "six hundred sixty six" },
        { id: 667, name: "six hundred sixty seven" },
        { id: 668, name: "six hundred sixty eight" },
        { id: 669, name: "six hundred sixty nine" },
        { id: 670, name: "six hundred seventy" },
        { id: 671, name: "six hundred seventy one" },
        { id: 672, name: "six hundred seventy two" },
        { id: 673, name: "six hundred seventy three" },
        { id: 674, name: "six hundred seventy four" },
        { id: 675, name: "six hundred seventy five" },
        { id: 676, name: "six hundred seventy six" },
        { id: 677, name: "six hundred seventy seven" },
        { id: 678, name: "six hundred seventy eight" },
        { id: 679, name: "six hundred seventy nine" },
        { id: 680, name: "six hundred eighty" },
        { id: 681, name: "six hundred eighty one" },
        { id: 682, name: "six hundred eighty two" },
        { id: 683, name: "six hundred eighty three" },
        { id: 684, name: "six hundred eighty four" },
        { id: 685, name: "six hundred eighty five" },
        { id: 686, name: "six hundred eighty six" },
        { id: 687, name: "six hundred eighty seven" },
        { id: 688, name: "six hundred eighty eight" },
        { id: 689, name: "six hundred eighty nine" },
        { id: 690, name: "six hundred ninety" },
        { id: 691, name: "six hundred ninety one" },
        { id: 692, name: "six hundred ninety two" },
        { id: 693, name: "six hundred ninety three" },
        { id: 694, name: "six hundred ninety four" },
        { id: 695, name: "six hundred ninety five" },
        { id: 696, name: "six hundred ninety six" },
        { id: 697, name: "six hundred ninety seven" },
        { id: 698, name: "six hundred ninety eight" },
        { id: 699, name: "six hundred ninety nine" },
        { id: 700, name: "seven hundred" },
        { id: 701, name: "seven hundred one" },
        { id: 702, name: "seven hundred two" },
        { id: 703, name: "seven hundred three" },
        { id: 704, name: "seven hundred four" },
        { id: 705, name: "seven hundred five" },
        { id: 706, name: "seven hundred six" },
        { id: 707, name: "seven hundred seven" },
        { id: 708, name: "seven hundred eight" },
        { id: 709, name: "seven hundred nine" },
        { id: 710, name: "seven hundred ten" },
        { id: 711, name: "seven hundred eleven" },
        { id: 712, name: "seven hundred twelve" },
        { id: 713, name: "seven hundred thirteen" },
        { id: 714, name: "seven hundred fourteen" },
        { id: 715, name: "seven hundred fifteen" },
        { id: 716, name: "seven hundred sixteen" },
        { id: 717, name: "seven hundred seventeen" },
        { id: 718, name: "seven hundred eighteen" },
        { id: 719, name: "seven hundred nineteen" },
        { id: 720, name: "seven hundred twenty" },
        { id: 721, name: "seven hundred twenty one" },
        { id: 722, name: "seven hundred twenty two" },
        { id: 723, name: "seven hundred twenty three" },
        { id: 724, name: "seven hundred twenty four" },
        { id: 725, name: "seven hundred twenty five" },
        { id: 726, name: "seven hundred twenty six" },
        { id: 727, name: "seven hundred twenty seven" },
        { id: 728, name: "seven hundred twenty eight" },
        { id: 729, name: "seven hundred twenty nine" },
        { id: 730, name: "seven hundred thirty" },
        { id: 731, name: "seven hundred thirty one" },
        { id: 732, name: "seven hundred thirty two" },
        { id: 733, name: "seven hundred thirty three" },
        { id: 734, name: "seven hundred thirty four" },
        { id: 735, name: "seven hundred thirty five" },
        { id: 736, name: "seven hundred thirty six" },
        { id: 737, name: "seven hundred thirty seven" },
        { id: 738, name: "seven hundred thirty eight" },
        { id: 739, name: "seven hundred thirty nine" },
        { id: 740, name: "seven hundred forty" },
        { id: 741, name: "seven hundred forty one" },
        { id: 742, name: "seven hundred forty two" },
        { id: 743, name: "seven hundred forty three" },
        { id: 744, name: "seven hundred forty four" },
        { id: 745, name: "seven hundred forty five" },
        { id: 746, name: "seven hundred forty six" },
        { id: 747, name: "seven hundred forty seven" },
        { id: 748, name: "seven hundred forty eight" },
        { id: 749, name: "seven hundred forty nine" },
        { id: 750, name: "seven hundred fifty" },
        { id: 751, name: "seven hundred fifty one" },
        { id: 752, name: "seven hundred fifty two" },
        { id: 753, name: "seven hundred fifty three" },
        { id: 754, name: "seven hundred fifty four" },
        { id: 755, name: "seven hundred fifty five" },
        { id: 756, name: "seven hundred fifty six" },
        { id: 757, name: "seven hundred fifty seven" },
        { id: 758, name: "seven hundred fifty eight" },
        { id: 759, name: "seven hundred fifty nine" },
        { id: 760, name: "seven hundred sixty" },
        { id: 761, name: "seven hundred sixty one" },
        { id: 762, name: "seven hundred sixty two" },
        { id: 763, name: "seven hundred sixty three" },
        { id: 764, name: "seven hundred sixty four" },
        { id: 765, name: "seven hundred sixty five" },
        { id: 766, name: "seven hundred sixty six" },
        { id: 767, name: "seven hundred sixty seven" },
        { id: 768, name: "seven hundred sixty eight" },
        { id: 769, name: "seven hundred sixty nine" },
        { id: 770, name: "seven hundred seventy" },
        { id: 771, name: "seven hundred seventy one" },
        { id: 772, name: "seven hundred seventy two" },
        { id: 773, name: "seven hundred seventy three" },
        { id: 774, name: "seven hundred seventy four" },
        { id: 775, name: "seven hundred seventy five" },
        { id: 776, name: "seven hundred seventy six" },
        { id: 777, name: "seven hundred seventy seven" },
        { id: 778, name: "seven hundred seventy eight" },
        { id: 779, name: "seven hundred seventy nine" },
        { id: 780, name: "seven hundred eighty" },
        { id: 781, name: "seven hundred eighty one" },
        { id: 782, name: "seven hundred eighty two" },
        { id: 783, name: "seven hundred eighty three" },
        { id: 784, name: "seven hundred eighty four" },
        { id: 785, name: "seven hundred eighty five" },
        { id: 786, name: "seven hundred eighty six" },
        { id: 787, name: "seven hundred eighty seven" },
        { id: 788, name: "seven hundred eighty eight" },
        { id: 789, name: "seven hundred eighty nine" },
        { id: 790, name: "seven hundred ninety" },
        { id: 791, name: "seven hundred ninety one" },
        { id: 792, name: "seven hundred ninety two" },
        { id: 793, name: "seven hundred ninety three" },
        { id: 794, name: "seven hundred ninety four" },
        { id: 795, name: "seven hundred ninety five" },
        { id: 796, name: "seven hundred ninety six" },
        { id: 797, name: "seven hundred ninety seven" },
        { id: 798, name: "seven hundred ninety eight" },
        { id: 799, name: "seven hundred ninety nine" },
        { id: 800, name: "eight hundred" },
        { id: 801, name: "eight hundred one" },
        { id: 802, name: "eight hundred two" },
        { id: 803, name: "eight hundred three" },
        { id: 804, name: "eight hundred four" },
        { id: 805, name: "eight hundred five" },
        { id: 806, name: "eight hundred six" },
        { id: 807, name: "eight hundred seven" },
        { id: 808, name: "eight hundred eight" },
        { id: 809, name: "eight hundred nine" },
        { id: 810, name: "eight hundred ten" },
        { id: 811, name: "eight hundred eleven" },
        { id: 812, name: "eight hundred twelve" },
        { id: 813, name: "eight hundred thirteen" },
        { id: 814, name: "eight hundred fourteen" },
        { id: 815, name: "eight hundred fifteen" },
        { id: 816, name: "eight hundred sixteen" },
        { id: 817, name: "eight hundred seventeen" },
        { id: 818, name: "eight hundred eighteen" },
        { id: 819, name: "eight hundred nineteen" },
        { id: 820, name: "eight hundred twenty" },
        { id: 821, name: "eight hundred twenty one" },
        { id: 822, name: "eight hundred twenty two" },
        { id: 823, name: "eight hundred twenty three" },
        { id: 824, name: "eight hundred twenty four" },
        { id: 825, name: "eight hundred twenty five" },
        { id: 826, name: "eight hundred twenty six" },
        { id: 827, name: "eight hundred twenty seven" },
        { id: 828, name: "eight hundred twenty eight" },
        { id: 829, name: "eight hundred twenty nine" },
        { id: 830, name: "eight hundred thirty" },
        { id: 831, name: "eight hundred thirty one" },
        { id: 832, name: "eight hundred thirty two" },
        { id: 833, name: "eight hundred thirty three" },
        { id: 834, name: "eight hundred thirty four" },
        { id: 835, name: "eight hundred thirty five" },
        { id: 836, name: "eight hundred thirty six" },
        { id: 837, name: "eight hundred thirty seven" },
        { id: 838, name: "eight hundred thirty eight" },
        { id: 839, name: "eight hundred thirty nine" },
        { id: 840, name: "eight hundred forty" },
        { id: 841, name: "eight hundred forty one" },
        { id: 842, name: "eight hundred forty two" },
        { id: 843, name: "eight hundred forty three" },
        { id: 844, name: "eight hundred forty four" },
        { id: 845, name: "eight hundred forty five" },
        { id: 846, name: "eight hundred forty six" },
        { id: 847, name: "eight hundred forty seven" },
        { id: 848, name: "eight hundred forty eight" },
        { id: 849, name: "eight hundred forty nine" },
        { id: 850, name: "eight hundred fifty" },
        { id: 851, name: "eight hundred fifty one" },
        { id: 852, name: "eight hundred fifty two" },
        { id: 853, name: "eight hundred fifty three" },
        { id: 854, name: "eight hundred fifty four" },
        { id: 855, name: "eight hundred fifty five" },
        { id: 856, name: "eight hundred fifty six" },
        { id: 857, name: "eight hundred fifty seven" },
        { id: 858, name: "eight hundred fifty eight" },
        { id: 859, name: "eight hundred fifty nine" },
        { id: 860, name: "eight hundred sixty" },
        { id: 861, name: "eight hundred sixty one" },
        { id: 862, name: "eight hundred sixty two" },
        { id: 863, name: "eight hundred sixty three" },
        { id: 864, name: "eight hundred sixty four" },
        { id: 865, name: "eight hundred sixty five" },
        { id: 866, name: "eight hundred sixty six" },
        { id: 867, name: "eight hundred sixty seven" },
        { id: 868, name: "eight hundred sixty eight" },
        { id: 869, name: "eight hundred sixty nine" },
        { id: 870, name: "eight hundred seventy" },
        { id: 871, name: "eight hundred seventy one" },
        { id: 872, name: "eight hundred seventy two" },
        { id: 873, name: "eight hundred seventy three" },
        { id: 874, name: "eight hundred seventy four" },
        { id: 875, name: "eight hundred seventy five" },
        { id: 876, name: "eight hundred seventy six" },
        { id: 877, name: "eight hundred seventy seven" },
        { id: 878, name: "eight hundred seventy eight" },
        { id: 879, name: "eight hundred seventy nine" },
        { id: 880, name: "eight hundred eighty" },
        { id: 881, name: "eight hundred eighty one" },
        { id: 882, name: "eight hundred eighty two" },
        { id: 883, name: "eight hundred eighty three" },
        { id: 884, name: "eight hundred eighty four" },
        { id: 885, name: "eight hundred eighty five" },
        { id: 886, name: "eight hundred eighty six" },
        { id: 887, name: "eight hundred eighty seven" },
        { id: 888, name: "eight hundred eighty eight" },
        { id: 889, name: "eight hundred eighty nine" },
        { id: 890, name: "eight hundred ninety" },
        { id: 891, name: "eight hundred ninety one" },
        { id: 892, name: "eight hundred ninety two" },
        { id: 893, name: "eight hundred ninety three" },
        { id: 894, name: "eight hundred ninety four" },
        { id: 895, name: "eight hundred ninety five" },
        { id: 896, name: "eight hundred ninety six" },
        { id: 897, name: "eight hundred ninety seven" },
        { id: 898, name: "eight hundred ninety eight" },
        { id: 899, name: "eight hundred ninety nine" },
        { id: 900, name: "nine hundred" },
        { id: 901, name: "nine hundred one" },
        { id: 902, name: "nine hundred two" },
        { id: 903, name: "nine hundred three" },
        { id: 904, name: "nine hundred four" },
        { id: 905, name: "nine hundred five" },
        { id: 906, name: "nine hundred six" },
        { id: 907, name: "nine hundred seven" },
        { id: 908, name: "nine hundred eight" },
        { id: 909, name: "nine hundred nine" },
        { id: 910, name: "nine hundred ten" },
        { id: 911, name: "nine hundred eleven" },
        { id: 912, name: "nine hundred twelve" },
        { id: 913, name: "nine hundred thirteen" },
        { id: 914, name: "nine hundred fourteen" },
        { id: 915, name: "nine hundred fifteen" },
        { id: 916, name: "nine hundred sixteen" },
        { id: 917, name: "nine hundred seventeen" },
        { id: 918, name: "nine hundred eighteen" },
        { id: 919, name: "nine hundred nineteen" },
        { id: 920, name: "nine hundred twenty" },
        { id: 921, name: "nine hundred twenty one" },
        { id: 922, name: "nine hundred twenty two" },
        { id: 923, name: "nine hundred twenty three" },
        { id: 924, name: "nine hundred twenty four" },
        { id: 925, name: "nine hundred twenty five" },
        { id: 926, name: "nine hundred twenty six" },
        { id: 927, name: "nine hundred twenty seven" },
        { id: 928, name: "nine hundred twenty eight" },
        { id: 929, name: "nine hundred twenty nine" },
        { id: 930, name: "nine hundred thirty" },
        { id: 931, name: "nine hundred thirty one" },
        { id: 932, name: "nine hundred thirty two" },
        { id: 933, name: "nine hundred thirty three" },
        { id: 934, name: "nine hundred thirty four" },
        { id: 935, name: "nine hundred thirty five" },
        { id: 936, name: "nine hundred thirty six" },
        { id: 937, name: "nine hundred thirty seven" },
        { id: 938, name: "nine hundred thirty eight" },
        { id: 939, name: "nine hundred thirty nine" },
        { id: 940, name: "nine hundred forty" },
        { id: 941, name: "nine hundred forty one" },
        { id: 942, name: "nine hundred forty two" },
        { id: 943, name: "nine hundred forty three" },
        { id: 944, name: "nine hundred forty four" },
        { id: 945, name: "nine hundred forty five" },
        { id: 946, name: "nine hundred forty six" },
        { id: 947, name: "nine hundred forty seven" },
        { id: 948, name: "nine hundred forty eight" },
        { id: 949, name: "nine hundred forty nine" },
        { id: 950, name: "nine hundred fifty" },
        { id: 951, name: "nine hundred fifty one" },
        { id: 952, name: "nine hundred fifty two" },
        { id: 953, name: "nine hundred fifty three" },
        { id: 954, name: "nine hundred fifty four" },
        { id: 955, name: "nine hundred fifty five" },
        { id: 956, name: "nine hundred fifty six" },
        { id: 957, name: "nine hundred fifty seven" },
        { id: 958, name: "nine hundred fifty eight" },
        { id: 959, name: "nine hundred fifty nine" },
        { id: 960, name: "nine hundred sixty" },
        { id: 961, name: "nine hundred sixty one" },
        { id: 962, name: "nine hundred sixty two" },
        { id: 963, name: "nine hundred sixty three" },
        { id: 964, name: "nine hundred sixty four" },
        { id: 965, name: "nine hundred sixty five" },
        { id: 966, name: "nine hundred sixty six" },
        { id: 967, name: "nine hundred sixty seven" },
        { id: 968, name: "nine hundred sixty eight" },
        { id: 969, name: "nine hundred sixty nine" },
        { id: 970, name: "nine hundred seventy" },
        { id: 971, name: "nine hundred seventy one" },
        { id: 972, name: "nine hundred seventy two" },
        { id: 973, name: "nine hundred seventy three" },
        { id: 974, name: "nine hundred seventy four" },
        { id: 975, name: "nine hundred seventy five" },
        { id: 976, name: "nine hundred seventy six" },
        { id: 977, name: "nine hundred seventy seven" },
        { id: 978, name: "nine hundred seventy eight" },
        { id: 979, name: "nine hundred seventy nine" },
        { id: 980, name: "nine hundred eighty" },
        { id: 981, name: "nine hundred eighty one" },
        { id: 982, name: "nine hundred eighty two" },
        { id: 983, name: "nine hundred eighty three" },
        { id: 984, name: "nine hundred eighty four" },
        { id: 985, name: "nine hundred eighty five" },
        { id: 986, name: "nine hundred eighty six" },
        { id: 987, name: "nine hundred eighty seven" },
        { id: 988, name: "nine hundred eighty eight" },
        { id: 989, name: "nine hundred eighty nine" },
        { id: 990, name: "nine hundred ninety" },
        { id: 991, name: "nine hundred ninety one" },
        { id: 992, name: "nine hundred ninety two" },
        { id: 993, name: "nine hundred ninety three" },
        { id: 994, name: "nine hundred ninety four" },
        { id: 995, name: "nine hundred ninety five" },
        { id: 996, name: "nine hundred ninety six" },
        { id: 997, name: "nine hundred ninety seven" },
        { id: 998, name: "nine hundred ninety eight" },
        { id: 999, name: "nine hundred ninety nine" },
        { id: 1000, name: "one thousand" },
    ];

    let user = users.find(item => item.id === number);
    return user.name;
};